console.log("ok start");
console.log("         \n                         he he..........");
var a;
console.log(a);
a = 12;
console.log(a);
var b;
console.log(b);
b = null;
console.log(b);
b = 12.32;
console.log(b);
b = 12;
console.log(b);
b = true;
console.log(b);
b = "qwe";
console.log(b);
var c;
console.log(c);
c = undefined;
console.log(c);
c = null;
console.log(c);
var d;
console.log(d);
